In [1]:
import numpy as np
np.random.seed(0)


In [4]:
np.linspace(0, 10)

array([1, 2, 3])

In [5]:
x = np.arange(12).reshape((3, 4))
print(x[0][0])
print(x[0, 0])

0
0


In [7]:
r1 = x[0, :]
r1

array([0, 1, 2, 3])

In [8]:
r1[2] = 10
print(r1)
print(x)

[ 0  1 10  3]
[[ 0  1 10  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
A = np.arange(12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
B = A.reshape((3,4))
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
C = np.arange(12, 24)
C

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [17]:
np.concatenate([A, C])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [24]:
big_array = np.random.randint(1, 100, size=100000)
compute_reciprocals(big_array)

array([0.01666667, 0.02702703, 0.01492537, ..., 0.015625  , 1.        ,
       0.01369863])

In [25]:
(1.0 / big_array)

array([0.01666667, 0.02702703, 0.01492537, ..., 0.015625  , 1.        ,
       0.01369863])

In [27]:
n = np.divide(1.0, big_array)

In [34]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
print(B.sum(axis=0))
print(B.sum(axis=1))

[12 15 18 21]
[ 6 22 38]


In [39]:
B.sum(axis=1)

array([ 6, 22, 38])

In [50]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
D = np.random.randint(1, 11, size=12)
D

array([ 1,  3,  2,  1,  4,  6,  7,  8,  9,  2,  2, 10])

In [51]:
A < D

array([ True,  True, False, False, False,  True,  True,  True,  True,
       False, False, False])

In [54]:
ind = [1, 3, 4]
D[ind]

array([3, 1, 4])