In [1]:
import numpy as np
np.random.seed(0)

In [6]:
print(np.linspace(0, 10, num=10))
print(np.array([1, 2, 3]))

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[1 2 3]


In [14]:
A = np.arange(12).reshape((3,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
B = A[:2, :3]
B

array([[0, 1, 2],
       [4, 5, 6]])

In [20]:
A = np.arange(12)
B = A.reshape((3,4))
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [25]:
big_array = np.random.randint(1, 100, size=100000)
%timeit compute_reciprocals(big_array)


175 ms ± 605 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
%timeit (1.0 / big_array)

116 µs ± 1.26 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [28]:
compute_reciprocals(big_array)

array([0.01388889, 0.05      , 0.015625  , ..., 0.0106383 , 0.01886792,
       0.01041667])

In [30]:
1.0 / big_array

array([0.01388889, 0.05      , 0.015625  , ..., 0.0106383 , 0.01886792,
       0.01041667])

In [32]:
np.divide(1.0, big_array)

array([0.01388889, 0.05      , 0.015625  , ..., 0.0106383 , 0.01886792,
       0.01041667])

In [33]:
print(big_array.min())
print(big_array.max())

1
99


In [34]:
np.max(big_array)

99

In [36]:
print(sum(big_array))
print(np.sum(big_array))
print(big_array.sum())

4988793
4988793
4988793


In [37]:
sum(big_array) / len(big_array)

49.88793

In [40]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
B.sum(axis=0)

array([12, 15, 18, 21])

In [43]:
B.sum(axis=1)

array([ 6, 22, 38])

In [48]:
X = np.random.randint(1, 100, size=12)
Y = np.random.randint(1, 100, size=12)
print(X)
print(Y)

[ 9 21 99 77 66 66 41 94  1 56 74 29]
[90 36 75  4 51 37 99 89 30 46 55 32]


In [52]:
X > 70

array([False, False,  True,  True, False, False, False,  True, False,
       False,  True, False])

In [53]:
X[X > 70]

array([99, 77, 94, 74])

In [55]:
ind = [0, 1, 3]
Y[ind]

array([90, 36,  4])